services:
  configserver:
    image: vishalsaini410/config-server:1.0.0
    container_name: "configserver"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
#          these are done to run the config server a little bit early than other svcs
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - payroll


  leave:
    image: vishalsaini410/leave:1.0.0
    container_name: "leave"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    networks:
      - payroll

networks:
  payroll:
    driver: "bridge"