server:
  port: 8080
spring:
  application:
    name: leave
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    function:
      definition: sendCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase
#    username: root
#    password: rootpassword
#
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka : true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "Leave MS"
    description: "LEAVE MS for Payroll"
    version : "1.0.0"